###################  spring配置  ###################
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.10.94:3306/sznews?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: bYb123456.
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      initial-size: 1
      max-wait: 60000
      min-idle: 20
      remove-abandoned: true
      remove-abandoned-timeout: 180
      connection-properties: clientEncoding=UTF-8
  mvc:
    favicon:
      enabled: false
  ################### redis 配置 ###################
  redis:
    host: 127.0.0.1
    port: 6379
    password: ''
    pool:
      max-active: 30
      max-wait: 100
      max-idle: 30
      min-idle: 5
    timeout: 6000
    # 0-15
    database: 0
  cache:
    packages: com.byb.service
  # spring-session 配置
  session:
    store-type: redis
    timeout: 1800
  servlet:
    session:
      timeout: 1800
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

###################  mybatis配置  ###################
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.byb.entity, com.byb.form, com.byb.bo, com.byb.vo
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
# 打印sql
logging:
  path: /root/sznews-log/
  level:
    com.byb.dao: DEBUG
    com.byb.service: INFO, ERROR
server:
  port: 8068
  tomcat:
    # 最大连接数
    max-connections: 200
    max-threads: 1000
############### 基本信息配置 ####################
photo:
  path: /usr/local/image/
  remote: 'http://192.168.10.39/image/'
swagger:
  show: true